-- 코드를 입력하세요
SELECT I.NAME, I.DATETIME
FROM(
    SELECT A.NAME,A.DATETIME, RANK() OVER(ORDER BY A.DATETIME ASC) AS R
    FROM ANIMAL_INS AS A
    WHERE NOT EXISTS(
    SELECT B.ANIMAL_ID
    FROM ANIMAL_OUTS AS B
    WHERE B.ANIMAL_ID = A.ANIMAL_ID)
    ) AS I
    WHERE I.R <= 3;